spring:
  config:
    import: optional:file:/secrets/application-secret.yml

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins:
              - 'https://paydeuk.com'
              - 'https://www.paydeuk.com'
            allowedHeaders:
              - 'Content-Type'
              - 'Authorization'
              - 'Access-Control-Allow-Origin'  # CORS 헤더 포함
            allowedMethods:
              - PUT
              - PATCH
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: paydeuk-service
          uri: http://internal-alb-internal-509933267.ap-northeast-2.elb.amazonaws.com
          predicates:
            - Path=/service/**
          filters:
            - AccessTokenValidationGatewayFilter

        - id: paydeuk-module
          uri: http://internal-alb-internal-509933267.ap-northeast-2.elb.amazonaws.com
          predicates:
            - Path=/module/**
          filters:
            - AccessTokenValidationGatewayFilter

        - id: paydeuk-auth-refresh
          uri: http://internal-alb-internal-509933267.ap-northeast-2.elb.amazonaws.com
          predicates:
            - Path=/auth/api/refresh
          filters:
            - RefreshTokenValidationGatewayFilter

        - id: paydeuk-auth-logout
          uri: http://internal-alb-internal-509933267.ap-northeast-2.elb.amazonaws.com
          predicates:
            - Path=/auth/api/logout
          filters:
            - AccessTokenValidationGatewayFilter

        - id: paydeuk-auth
          uri: http://internal-alb-internal-509933267.ap-northeast-2.elb.amazonaws.com
          predicates:
            - Path=/auth/**

error:
  printStackTrace: true # Stack trace 출력 여부
  printStackTraceLine: 10 # Stack trace 출력 줄 수

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

logging:
  level:
    root: INFO