server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

spring:
  config:
    import: application-secret.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: paydeuk-service
          uri: http://localhost:8081
          predicates:
            - Path=/service/**
          filters:
            - AccessTokenValidationGatewayFilter

        - id: paydeuk-module
          uri: http://localhost:8082
          predicates:
            - Path=/module/**
          filters:
            - AccessTokenValidationGatewayFilter

        - id: paydeuk-auth-refresh
          uri: http://localhost:8083
          predicates:
            - Path=/auth/api/refresh
          filters:
            - RefreshTokenValidationGatewayFilter

        - id: paydeuk-auth
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**

error:
  printStackTrace: true # Stack trace 출력 여부
  printStackTraceLine: 10 # Stack trace 출력 줄 수

logging:
  level:
    reactor.netty.http.server: DEBUG